In [ ]:
import numpy as np
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:

ones=np.arange(0,10,3)
print(ones)

[0 3 6 9]


In [ ]:
linspace=np.linspace()

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [ ]:
import numpy as np
arr=np.array([[2,3,4],[6,7,8]])
print(arr.size)
print(arr.shape)
print(arr.ndim)

6
(2, 3)
2


In [ ]:
import numpy as np
arr1=np.array([4,6,8])
arr2 =np.array([3,4,5])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[ 7 10 13]
[1 2 3]
[12 24 40]
[1.33333333 1.5        1.6       ]


In [ ]:
import numpy as np
arr=np.array([[1,2] ,[4,5]])
print(arr.sum())
print(arr.mean())


12
3.0


In [ ]:
import numpy as np
arr=np.array([1,3,2,4,5,56,67,7])
print(arr[1:4])

[3 2 4]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
print(a+b)
print(a*b)
print(a-b)




[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]


In [ ]:
arr=np.array([[1,2],[3,4]])
print(arr)
print(arr.T)

In [ ]:


import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped = a1.reshape(2, 4)  # This will throw an error because reshaping to (2, 4) is not possible

print(reshaped)
print(a1)

In [39]:
rand=np.random.rand(3,2)
print(rand)

[[0.07635533 0.15481421]
 [0.1284314  0.28812413]
 [0.15272035 0.75024399]]


In [40]:

integers=np.random.randint(1,10(2,2))
print(integers)

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\ANJALI KUMARI\AppData\Local\Temp\ipykernel_30508\1625758064.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  integers=np.random.randint(1,10(2,2))


TypeError: 'int' object is not callable