In [1]:
print("we are learning the numpy libary of python")

we are learning the numpy libary of python


In [2]:
import numpy as np 
# create an array
arr=np.array([11,22,33,44,222])
print(arr)

[ 11  22  33  44 222]


In [5]:
# perform the mathematical operation
print(arr+10)
print(arr*2)
print(arr-1)
print(arr)

[ 21  32  43  54 232]
[ 22  44  66  88 444]
[ 10  21  32  43 221]
[ 11  22  33  44 222]


In [9]:
# Create the 2D array.
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
print(arr1 * 3)

[[ 3  6]
 [ 9 12]]
